version: '3'

services:
  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
    networks:
      - app-network

  api:
    container_name: api
    ports:
      - '3000:3000'
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules
    networks:
      - app-network
    depends_on:
      - database

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
