version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
    networks:
      - app-network

  api:
    container_name: bloodboiler-mongodb-api
    build:
      context: .
      target: ${NODE_ENV}
    image: bloodboiler-mongodb:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
